apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: clienteapi-listener
  namespace: dummy-tekton-001 
spec:
  serviceAccountName: pipeline

  triggers:
    - triggerRef: disparador-dummy-micro-01
