
apiVersion: project.openshift.io/v1
kind: Project
metadata:
  name: dummy-tekton-001

---

apiVersion: v1
kind: LimitRange
metadata:
  name: limit-mem-cpu-per-container
  namespace: dummy-tekton-001 
spec:
  limits:
  - type: Container
    max:
      cpu: "1000m"
      memory: "2Gi"
    min:
      cpu: "100m"
      memory: "1Gi"
      
    default:
      cpu: "700m"
      memory: "1Gi"
      
    defaultRequest:
      cpu: "500m"
      memory: "1Gi"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: source-pvc
  namespace: dummy-tekton-001 
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
      
---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: pipeline
  namespace: dummy-tekton-001 
  
---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: tekton-triggers-example-minimal
  namespace: dummy-tekton-001 
rules:
# EventListeners need to be able to fetch all namespaced resources
- apiGroups: ["triggers.tekton.dev"]
  resources: ["eventlisteners", "triggerbindings", "triggertemplates", "triggers"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
# configmaps is needed for updating logging config
  resources: ["configmaps"]
  verbs: ["get", "list", "watch"]
# Permissions to create resources in associated TriggerTemplates
- apiGroups: ["tekton.dev"]
  resources: ["pipelineruns", "pipelineresources", "taskruns"]
  verbs: ["create"]
- apiGroups: [""]
  resources: ["serviceaccounts"]
  verbs: ["impersonate"]
- apiGroups: ["policy"]
  resources: ["podsecuritypolicies"]
  resourceNames: ["tekton-triggers"]
  verbs: ["use"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tekton-triggers-example-binding
  namespace: dummy-tekton-001 
subjects:
- kind: ServiceAccount
  name: pipeline
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: tekton-triggers-example-minimal

---

kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: tekton-triggers-example-clusterrole
  namespace: dummy-tekton-001 
rules:
  # EventListeners need to be able to fetch any clustertriggerbindings
- apiGroups: ["triggers.tekton.dev"]
  resources: ["clustertriggerbindings", "clusterinterceptors"]
  verbs: ["get", "list", "watch"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tekton-triggers-example-clusterbinding
  namespace: dummy-tekton-001 
subjects:
- kind: ServiceAccount
  name: pipeline
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tekton-triggers-example-clusterrole      

---

apiVersion: v1
kind: Secret
metadata:
  name: github-interceptor-secret
  namespace: dummy-tekton-001 
type: Opaque
stringData:
  secretToken: "12345678"
  
  