
apiVersion: triggers.tekton.dev/v1alpha1
kind: Trigger
metadata:
  name: trig-dummy-micro-01
  namespace: dummy-tekton-001 
spec:
  serviceAccountName: pipeline
  bindings:
    - ref: trig-bind-dummy-micro-01
  template:
    name: trig-temp-dummy-micro-01
 
---
    
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: trig-temp-dummy-micro-01
  namespace: dummy-tekton-001 
spec:
  params:
  - name: git-repo-url
    description: EL REPOSITORIO DE GITHUB
    
  - name: git-revision
    description: NOMBRE DE 'RAMA' USADA EN GITHUB
    default: master
    
  - name: git-repo-name
    description: NOMBRE DEL RECURSO 'DEPLOYMENT' DE LA APLICACION A SER CREADO O ACTUALIZADO

  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      generateName: tekton-deploy-$(tt.params.git-repo-name)-
      namespace: dummy-tekton-001
    spec:
      serviceAccountName: pipeline
      pipelineRef:
        name: pipeline-build-and-deploy
      params:
      - name: git-repo-name
        value: $(tt.params.git-repo-name)
  
      - name: git-repo-url
        value: $(tt.params.git-repo-url)
        
      - name: git-revision
        value: $(tt.params.git-revision)
        
      - name: IMAGE
        #value: image-registry.openshift-image-registry.svc:5000/dummy-tekton-001/$(tt.params.git-repo-name)
        value: image-registry.openshift-image-registry.svc:5000/dummy-tekton-001/dummy-micro-01:latest
        
      workspaces:
      - name: workspace-pipeline
        persistentVolumeClaim:
          claimName: source-pvc

---

apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: trig-bind-dummy-micro-01
  namespace: dummy-tekton-001 
spec:
  params:  
  - name: git-repo-url
    value: $(body.repository.url)
    
  - name: git-repo-name
    value: $(body.repository.name)
    
  - name: git-revision
    value: $(body.head_commit.id)   

---

apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: listener-dummy-micro-01
  namespace: dummy-tekton-001 
spec:
  serviceAccountName: pipeline
  triggers:
    - triggerRef: trig-dummy-micro-01
