
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: integration-server
  namespace: dummy-tekton-003
spec:
  workspaces:
  - name: source
  params:
    - name: directorio-yaml
      description: DIRECTORIO QUE CONTIENE LOS YAML PARA EL DESPLIEGUE DE LA APLICACION
      type: string
      default: "apps"
  steps:
    - name: aplicacion-yaml
      image: image-registry.openshift-image-registry.svc:5000/openshift/cli:latest
      workingDir: /workspace/source
      command: ["/bin/bash", "-c"]
      args:
        - |-
          echo APLICANDO 'YAMLs' DEL DIRECTORIO: [$(inputs.params.directorio-yaml)]
          oc apply -f $(inputs.params.directorio-yaml)
          echo -----------------------------------

---

apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: task-actualizar-aplicacion
  namespace: dummy-tekton-003
spec:
  params:
    - name: git-repo-name
      description: NOMBRE DEL RECURSO 'DEPLOYMENT' DE LA APLICACION
      type: string
      
    - name: IMAGE
      description: NOMBRE DEL RECURSO 'IMAGEN' CON LA CUAL SE REALIZARA LA ACTUALIZACION
      type: string
  steps:
    - name: patch
      image: image-registry.openshift-image-registry.svc:5000/openshift/cli:latest
      command: ["/bin/bash", "-c"]
      args:
        - |-
          echo ACTUALIZANDO RECURSO 'DEPLOYMENT' CON: [$(inputs.params.git-repo-name)]
          echo ACTUALIZANDO RECURSO 'DEPLOYMENT' CON: [$(inputs.params.IMAGE)]
          oc patch deployment $(inputs.params.git-repo-name) --patch='{"spec":{"template":{"spec":{
            "containers":[{
              "name": "$(inputs.params.git-repo-name)",
              "image":"$(inputs.params.IMAGE)"
            }]
          }}}}'

--- 
 
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: pipeline-ace-integracion-2
  namespace: dummy-tekton-003
spec:
  workspaces:
  - name: workspace-pipeline

  params:
  - name: git-repo-name
    type: string
    description: NOMBRE DEL RECURSO 'DEPLOYMENT' DE LA APLICACION
    default: "dummy-micro-deploy"
    
  - name: git-url
    type: string
    description: URL GITHUB DONDE ESTAN LOS YAML PARA EL DESPLIEGUE
    default: "https://github.com/selenia-viviana/repo-tekton-dummy-micro-01.git"
    
  - name: git-revision
    type: string
    description: NOMBRE DE RAMA USADA EN GITHUB
    default: "master" 
    
  - name: IMAGE
    type: string
    description: NOMBRE DEL RECURSO 'IMAGE' DE LA APLICACION
    default: "image-registry.openshift-image-registry.svc:5000/dummy-tekton-001/dummy-micro-01:latest" 
    
  tasks:
  - name: obtener-fuentes-repositorio
    taskref:
      name: git-clone
      kind: ClusterTask
    params:
    - name: url
      value: $(params.git-url)
    - name: subdirectory
      value: ""
    - name: deleteExisting
      value: "true"
    - name: revision
      value: $(params.git-revision)
    workspaces:
    - name: output
      workspace: workspace-pipeline


  - name: bar-file-test
    taskRef:
      name: buildah
      kind: ClusterTask
    params:
    - name: IMAGE
      value: $(params.IMAGE)
    - name: TLSVERIFY
      value: "false"
    workspaces:
    - name: source
      workspace: workspace-pipeline
    runafter:
    - obtener-fuentes-repositorio
    
    
  - name: update-template
    taskRef:
      name: integration-server
    workspaces:
    - name: source
      workspace: workspace-pipeline
    runafter:
    - bar-file-test
    
    
  - name: pipe-actualizar-aplicacion
    taskref:
      name: task-actualizar-aplicacion
    params:
    - name: git-repo-name
      value: $(params.git-repo-name)  
    - name: IMAGE
      value: $(params.IMAGE)
    runafter:
    - update-template
    
