
apiVersion: triggers.tekton.dev/v1alpha1
kind: Trigger
metadata:
  name: trig-dummy-micro-01
  namespace: dummy-tekton-001 
spec:
  serviceAccountName: pipeline
  bindings:
    - ref: trig-bind-dummy-micro-01
  template:
    name: trig-temp-dummy-micro-01
 
---
    
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: trig-temp-dummy-micro-01
  namespace: dummy-tekton-001 
spec:
  params:
  - name: url-github
    description: EL REPOSITORIO DE GITHUB
    
  - name: rama-github
    description: NOMBRE DE RAMA USADA EN GITHUB
    default: master
    
  - name: DEPLOYMENT
    description: NOMBRE DEL RECURSO 'DEPLOYMENT' DE LA APLICACION A SER CREADO O ACTUALIZADO

  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      generateName: tekton-deploy-$(tt.params.DEPLOYMENT)-
      namespace: dummy-tekton-001
    spec:
      serviceAccountName: pipeline
      pipelineRef:
        name: pipeline-build-and-deploy
      params:
      - name: DEPLOYMENT
        value: $(tt.params.DEPLOYMENT)
        
      - name: url-github
        value: $(tt.params.url-github)
        
      - name: rama-github
        value: $(tt.params.rama-github)
        
      - name: IMAGE
        #value: image-registry.openshift-image-registry.svc:5000/dummy-tekton-001/$(tt.params.DEPLOYMENT)
        value: image-registry.openshift-image-registry.svc:5000/dummy-tekton-001/dummy-micro-01:latest
        
      workspaces:
      - name: workspace-pipeline
        persistentVolumeClaim:
          claimName: source-pvc

---

apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: trig-bind-dummy-micro-01
  namespace: dummy-tekton-001 
spec:
  params:  
  - name: url-github
    value: $(body.repository.url)
    
  - name: DEPLOYMENT
    value: $(body.repository.name)
    
  - name: rama-githubn
    value: $(body.head_commit.id)   

---

apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: listener-dummy-micro-01
  namespace: dummy-tekton-001 
spec:
  serviceAccountName: pipeline
  triggers:
    - triggerRef: trig-dummy-micro-01
