
apiVersion: v1
kind: LimitRange
metadata:
  name: limit-mem-cpu-per-container
  namespace: dummy-tekton-004
spec:
  limits:
  - type: Container
    max:
      cpu: "1000m"
      memory: "2Gi"
    min:
      cpu: "100m"
      memory: "1Gi"
      
    default:
      cpu: "700m"
      memory: "1Gi"
      
    defaultRequest:
      cpu: "500m"
      memory: "1Gi"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: source-pvc
  namespace: dummy-tekton-004
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi

---

apiVersion: v1
kind: Secret
metadata:
  name: github-interceptor-secret
  namespace: dummy-tekton-004
type: Opaque
stringData:
  secretToken: "12345678"

